ai model release fixes

diff --git a/.github/workflows/azure-static-web-apps-ashy-smoke-0bf195f1e.yml b/.github/workflows/azure-static-web-apps-ashy-smoke-0bf195f1e.yml
--- a/.github/workflows/azure-static-web-apps-ashy-smoke-0bf195f1e.yml
+++ b/.github/workflows/azure-static-web-apps-ashy-smoke-0bf195f1e.yml
@@ -69,11 +69,18 @@ jobs:
           GH_TOKEN: ${{ github.token }}
           TAG: ${{ env.AI_RELEASE_PREFIX }}/v${{ steps.training_params.outputs.version }}
         run: |
-          release_data="$(gh release view "$TAG")"
-          if echo "$release_data" | grep -F 'release not found' >/dev/null; then
-            echo "exists=false" >> "$GITHUB_OUTPUT"
-          else
+          set +e
+          error_output="$({ gh release view "$TAG" >/dev/null; } 2>&1)"; return_code=$?
+          set -e
+          echo $error_output
+          if [ $return_code -eq 0 ]; then
             echo "exists=true" >> "$GITHUB_OUTPUT"
+            exit 0
+          elif echo "$error_output" | grep -F 'release not found' >/dev/null; then
+            echo "exists=false" >> "$GITHUB_OUTPUT"
+            exit 0
+          else
+            exit 1
           fi
 
       # If release exists, use it for deployment
@@ -107,6 +114,7 @@ jobs:
           ${{ github.workspace }}/${{ env.AI_DIR }}/${{ env.AI_PARAMS_PATH }}
           --title "AI Search Model ${{ env.AI_RELEASE_PREFIX }} v${{ steps.training_params.outputs.version }}"
           --notes "${{ env.AI_RELEASE_NOTES }}"
+          --target "release/offline-only"
       
       - name: Set version file
         id: vars
